In [2]:

!pip install fg-data-profiling pandas numpy --quiet

In [4]:
import pandas as pd
import numpy as np
import data_profiling
from data_profiling import ProfileReport
from google.colab import files

In [5]:
uploaded =files.upload()

Saving messy_customer_orders.csv to messy_customer_orders.csv

In [6]:
df = pd.read_csv("messy_customer_orders.csv")

In [7]:
profile = ProfileReport(df, title="profiling Report", explorative =True )
profile.to_file('report.html')
files.download('report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]
  8%|▊         | 1/12 [00:00<00:06,  1.63it/s]
 17%|█▋        | 2/12 [00:00<00:03,  3.12it/s]
100%|██████████| 12/12 [00:05<00:00,  2.26it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
df.shape

(51000, 12)

In [9]:
df.dtypes

order_id           object
customer_id        object
order_date         object
country            object
category           object
product            object
quantity            int64
unit_price         object
total_amount      float64
status             object
payment_method     object
is_returned        object
dtype: object

In [11]:
df.isnull().sum()

order_id             0
customer_id       2033
order_date           0
country           2540
category          3052
product              0
quantity             0
unit_price        2033
total_amount      1528
status               0
payment_method       0
is_returned          0
dtype: int64

In [12]:
df.head(10)

     order_id customer_id   order_date  ...     status payment_method is_returned
0  ORD-004208   CUST-6426   22/07/2022  ...    Shipped         PayPal        TRUE
1  ORD-006584         NaN   10-12-2023  ...    Shipped           Cash        True
2  ORD-013539         NaN   26/07/2023  ...  Delivered         PayPal           1
3  ORD-038448   CUST-2286   02-18-2022  ...    shipped           Cash          No
4  ORD-022268   CUST-6074   18/06/2024  ...    pending  Bank Transfer           Y
5  ORD-003919         NaN   03/02/2023  ...    Pending           Cash        True
6  ORD-033802   CUST-1788   23/09/2023  ...    Pending         PayPal          no
7  ORD-034516   CUST-5877   10/07/2022  ...  Cancelled    Credit Card        True
8  ORD-026972   CUST-1165   15/04/2022  ...    Pending           Cash       False
9  ORD-022533   CUST-2637  21 Jun 2022  ...  delivered         PayPal       False

[10 rows x 12 columns]

In [13]:
df.tail(5)

         order_id customer_id  order_date  ...     status payment_method is_returned
50995  ORD-011285   CUST-1678  14/11/2022  ...  delivered           Cash          no
50996  ORD-044733   CUST-5264  07-16-2022  ...  cancelled  Bank Transfer       False
50997  ORD-038159   CUST-0710  2023-06-04  ...  Delivered           Cash       FALSE
50998  ORD-000861   CUST-4352  14/02/2024  ...  Cancelled           Cash          No
50999  ORD-015796   CUST-7019  2023-08-04  ...  cancelled    Credit Card           1

[5 rows x 12 columns]

In [14]:
df.columns=(
    df.columns
    .str.replace(' ','_')
    .str.lower()
    .str.strip()
)

In [15]:
missing =df.isnull().mean()*100
print(missing[missing>0].sort_values(ascending=False))

category        5.984314
country         4.980392
customer_id     3.986275
unit_price      3.986275
total_amount    2.996078
dtype: float64

In [16]:
n_dupes = df.duplicated().sum()

In [17]:
n_dupes

np.int64(1000)

In [18]:
df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head(10)

         order_id customer_id  ... payment_method is_returned
17684  ORD-000086   CUST-6333  ...  Bank Transfer        TRUE
18714  ORD-000086   CUST-6333  ...  Bank Transfer        TRUE
1064   ORD-000093   CUST-3114  ...           Cash       False
18156  ORD-000093   CUST-3114  ...           Cash       False
11092  ORD-000109   CUST-0585  ...         PayPal        TRUE
21365  ORD-000109   CUST-0585  ...         PayPal        TRUE
17112  ORD-000122   CUST-5638  ...         PayPal         yes
41112  ORD-000122   CUST-5638  ...         PayPal         yes
28614  ORD-000392   CUST-0765  ...    Credit Card          No
38436  ORD-000392   CUST-0765  ...    Credit Card          No

[10 rows x 12 columns]

In [19]:
df=df.drop_duplicates()

In [20]:
df.shape

(50000, 12)

In [21]:
df = df.copy()
#Numeric columns
for col in ['total_amount'] :
    df[col] = df[col].fillna(df[col].median())
#Categorical columns
categorical_cols = ['customer_id','country','category']

df[categorical_cols] = df[categorical_cols].fillna('Unknown')

In [23]:
print(df.isnull().sum()[df.isnull().sum() >0 ])

unit_price    2000
dtype: int64

In [67]:
for col in ['category','status','country']:
    df[col] = df[col].str.strip().str.lower()

#step 3 : map o canonical values
category_map = {
    'electronics': 'Electronics',
    'clothing': 'Clothing' ,
    'home & garden' : 'Home & Garden',
    'home and garden': 'Home & Garden',
    'sports': 'Sports',
    'books': 'Books',
    'unknown': 'Unknown'
}

status_map = {
    'pending': 'Pending',
    'shipped': 'Shipped',
    'delivered': 'Delivered',
    'cancelled': 'Cancelled'
}

country_map ={
    'united states': 'United States', 'us': 'United States',
    'u.s.a': 'United States', 'usa': 'United States',
    'united kingdom': 'United Kingdom', 'uk': 'United Kingdom','u.k.': 'United Kingdom',
    'australia': 'Australia', 'aus': 'Australia',
    'canada': 'Canada',
    'germany': 'Germany', 'de': 'Germany',
    'france': 'France', 'fr': 'France',
    'italy': 'Italy', 'it': 'Italy',
    'spain': 'Spain', 'es': 'Spain',
    'unknown': 'Unknown'
}

df['category'] = df['category'].map(category_map).fillna(df['category'])
df['status'] = df['status'].map(status_map).fillna(df['status'])
df['country'] = df['country'].map(country_map).fillna(df['country'])

In [36]:
df.head(10)

     order_id customer_id   order_date  ...     status payment_method is_returned
0  ORD-004208   CUST-6426   22/07/2022  ...    Shipped         PayPal        TRUE
1  ORD-006584     Unknown   10-12-2023  ...    Shipped           Cash        True
2  ORD-013539     Unknown   26/07/2023  ...  Delivered         PayPal           1
3  ORD-038448   CUST-2286   02-18-2022  ...    Shipped           Cash          No
4  ORD-022268   CUST-6074   18/06/2024  ...    Pending  Bank Transfer           Y
5  ORD-003919     Unknown   03/02/2023  ...    Pending           Cash        True
6  ORD-033802   CUST-1788   23/09/2023  ...    Pending         PayPal          no
7  ORD-034516   CUST-5877   10/07/2022  ...  Cancelled    Credit Card        True
8  ORD-026972   CUST-1165   15/04/2022  ...    Pending           Cash       False
9  ORD-022533   CUST-2637  21 Jun 2022  ...  Delivered         PayPal       False

[10 rows x 12 columns]

In [37]:
df['unit_price']=(
    df['unit_price']
    .astype(str)
    .str.replace(r'[$£,]','',regex=True) #commas catch 1,299.00 style values
    .str.strip()
)
df['unit_price'] = pd.to_numeric(df['unit_price'],errors='coerce')

In [38]:
df.head(10)

     order_id customer_id   order_date  ...     status payment_method is_returned
0  ORD-004208   CUST-6426   22/07/2022  ...    Shipped         PayPal        TRUE
1  ORD-006584     Unknown   10-12-2023  ...    Shipped           Cash        True
2  ORD-013539     Unknown   26/07/2023  ...  Delivered         PayPal           1
3  ORD-038448   CUST-2286   02-18-2022  ...    Shipped           Cash          No
4  ORD-022268   CUST-6074   18/06/2024  ...    Pending  Bank Transfer           Y
5  ORD-003919     Unknown   03/02/2023  ...    Pending           Cash        True
6  ORD-033802   CUST-1788   23/09/2023  ...    Pending         PayPal          no
7  ORD-034516   CUST-5877   10/07/2022  ...  Cancelled    Credit Card        True
8  ORD-026972   CUST-1165   15/04/2022  ...    Pending           Cash       False
9  ORD-022533   CUST-2637  21 Jun 2022  ...  Delivered         PayPal       False

[10 rows x 12 columns]

In [39]:
bool_map = {
    'Yes': True, 'yes': True, 'Y': True, 'y': True,
    'TRUE': True, 'True': True, 'true': True, '1': True, 1: True, True: True,
    'No': False, 'no': False, 'N': False, 'n': False,
    'FALSE': False, 'False': False, 'false': False, '0': False, 0: False, False: False
}
df['is_returned'] = df['is_returned'].map(bool_map).fillna(False)

In [40]:
df.head(10)

     order_id customer_id   order_date  ...     status payment_method is_returned
0  ORD-004208   CUST-6426   22/07/2022  ...    Shipped         PayPal        True
1  ORD-006584     Unknown   10-12-2023  ...    Shipped           Cash        True
2  ORD-013539     Unknown   26/07/2023  ...  Delivered         PayPal        True
3  ORD-038448   CUST-2286   02-18-2022  ...    Shipped           Cash       False
4  ORD-022268   CUST-6074   18/06/2024  ...    Pending  Bank Transfer        True
5  ORD-003919     Unknown   03/02/2023  ...    Pending           Cash        True
6  ORD-033802   CUST-1788   23/09/2023  ...    Pending         PayPal       False
7  ORD-034516   CUST-5877   10/07/2022  ...  Cancelled    Credit Card        True
8  ORD-026972   CUST-1165   15/04/2022  ...    Pending           Cash       False
9  ORD-022533   CUST-2637  21 Jun 2022  ...  Delivered         PayPal       False

[10 rows x 12 columns]

In [51]:
df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=False,errors='coerce')
# Fix remaining NaT — reload original raw strings for failed rows
df_raw_dates = pd.read_csv("messy_customer_orders.csv", usecols=['order_date'])
df_raw_dates.columns = ['order_date_raw']
df_raw_dates = df_raw_dates.loc[df.index]  # align index after drop_duplicates

mask = df['order_date'].isna()

# Try MM-DD-YYYY format
df.loc[mask, 'order_date'] = pd.to_datetime(
    df_raw_dates.loc[mask, 'order_date_raw'],
    format='%m-%d-%Y',
    errors='coerce'
)

mask2 = df['order_date'].isna()
print(f"NaT before: {mask.sum()}, NaT after: {mask2.sum()}")
# Second pass — fix "21 Jun 2022" and "21-Jun-22" text month formats
mask3 = df['order_date'].isna()

df.loc[mask3, 'order_date'] = pd.to_datetime(
    df_raw_dates.loc[mask3, 'order_date_raw'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

mask4 = df['order_date'].isna()
print(f"NaT before: {mask3.sum()}, NaT after: {mask4.sum()}")

failed=df['order_date'].isnull().sum()

NaT before: 27465, NaT after: 27465
NaT before: 27465, NaT after: 0

In [52]:
df.head(10)

     order_id customer_id order_date  ... order_year order_month order_day_of_week
0  ORD-004208   CUST-6426 2022-07-22  ...     2022.0         7.0            Friday
1  ORD-006584     Unknown 2023-10-12  ...        NaN         NaN               NaN
2  ORD-013539     Unknown 2023-07-26  ...     2023.0         7.0         Wednesday
3  ORD-038448   CUST-2286 2022-02-18  ...        NaN         NaN               NaN
4  ORD-022268   CUST-6074 2024-06-18  ...     2024.0         6.0           Tuesday
5  ORD-003919     Unknown 2023-02-03  ...     2023.0         2.0            Friday
6  ORD-033802   CUST-1788 2023-09-23  ...     2023.0         9.0          Saturday
7  ORD-034516   CUST-5877 2022-07-10  ...     2022.0         7.0            Sunday
8  ORD-026972   CUST-1165 2022-04-15  ...     2022.0         4.0            Friday
9  ORD-022533   CUST-2637 2022-06-21  ...        NaN         NaN               NaN

[10 rows x 15 columns]

In [70]:
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_day_of_week'] = df['order_date'].dt.day_name()

print(f"NaN in order_year: {df['order_year'].isna().sum()}")
print(f"NaN in order_month: {df['order_month'].isna().sum()}")
print(f"NaN in order_day_of_week: {df['order_day_of_week'].isna().sum()}")

NaN in order_year: 0
NaN in order_month: 0
NaN in order_day_of_week: 0

In [71]:
print(df[['order_date','order_year','order_month','order_day_of_week']].head())

  order_date  order_year  order_month order_day_of_week
0 2022-07-22        2022            7            Friday
1 2023-10-12        2023           10          Thursday
2 2023-07-26        2023            7         Wednesday
3 2022-02-18        2022            2            Friday
4 2024-06-18        2024            6           Tuesday

In [46]:
impossible_qty_mask = df['quantity'] <=0

In [57]:
print(df.loc[impossible_qty_mask,['order_id','product','quantity','unit_price','total_amount']].head())

        order_id              product  quantity  unit_price  total_amount
1     ORD-006584             Backpack        -2         NaN           NaN
306   ORD-029737             Yoga Mat        -3         NaN           NaN
686   ORD-036893           Sunglasses        -1       97.88        -97.88
847   ORD-017897           Sunglasses        -5       19.13        -95.65
1042  ORD-049788  Wireless Headphones        -2      274.32       -548.64

In [58]:
# Drop zero quantity rows (no transaction)
df = df[df['quantity'] != 0].copy()

# Recalculate total_amount from scratch
df['total_amount'] = df['quantity'] * df['unit_price']

print(f"Rows after removing zero quantity: {df.shape[0]}")
print(f"Remaining negative quantity (returns): {(df['quantity'] < 0).sum()}")

Rows after removing zero quantity: 49700
Remaining negative quantity (returns): 200

In [73]:
print("=== Final Data Quality Check ===")
print(f"Shape: {df.shape}")
print(f"NaT in order_date: {df['order_date'].isna().sum()}")
print(f"NaN in unit_price: {df['unit_price'].isna().sum()}")
print(f"NaN in order_year: {df['order_year'].isna().sum()}")
print(f"Negative quantity (returns): {(df['quantity'] < 0).sum()}")
print(f"Duplicates: {df.duplicated().sum()}")
print(f"\nCountry counts:\n{df['country'].value_counts()}")

=== Final Data Quality Check ===
Shape: (49700, 15)
NaT in order_date: 0
NaN in unit_price: 1989
NaN in order_year: 0
Negative quantity (returns): 200
Duplicates: 0

Country counts:
country
United States     11895
Germany            9011
Australia          8796
Canada             8779
United Kingdom     8733
Unknown            2486
Name: count, dtype: int64

In [74]:

# Export
from google.colab import files
df.to_csv('clean_customer_orders.csv', index=False)
files.download('clean_customer_orders.csv')
print("Exported.")

Exported.